apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-example-2
  namespace: cm-demo
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - cm-demo
    labelSelectors:
      'app': 'ben-knote'